In [5]:
# Crozier Kimball
# >>Homework found below after the "HOMEWORK" cell. 

In [6]:
import pandas as pd
path = 'https://raw.githubusercontent.com/lab30041954/Data/main/'
df = pd.read_csv(path + 'spam.csv')

In [7]:
df.shape

(4601, 52)

In [8]:
df.head()

word_make  word_address  word_all  word_3d  word_our  word_over  \
0       0.00          0.64      0.64      0.0      0.32       0.00   
1       0.21          0.28      0.50      0.0      0.14       0.28   
2       0.06          0.00      0.71      0.0      1.23       0.19   
3       0.00          0.00      0.00      0.0      0.63       0.00   
4       0.00          0.00      0.00      0.0      0.63       0.00   

   word_remove  word_internet  word_order  word_mail  ...  word_original  \
0         0.00           0.00        0.00       0.00  ...           0.00   
1         0.21           0.07        0.00       0.94  ...           0.00   
2         0.19           0.12        0.64       0.25  ...           0.12   
3         0.31           0.63        0.31       0.63  ...           0.00   
4         0.31           0.63        0.31       0.63  ...           0.00   

   word_project  word_re  word_edu  word_table  word_conference  cap_ave  \
0           0.0     0.00      0.00         0.0              0.0    3.756   
1           0.0     0.00      0.00         0.0              0.0    5.114   
2           0.0     0.06      0.06         0.0              0.0    9.821   
3           0.0     0.00      0.00         0.0              0.0    3.537   
4           0.0     0.00      0.00         0.0              0.0    3.537   

   cap_long  cap_total  spam  
0        61        278     1  
1       101       1028     1  
2       485       2259     1  
3        40        191     1  
4        40        191     1  

[5 rows x 52 columns]

In [9]:
round(df['spam'].mean(), 3)

np.float64(0.394)

In [10]:
y = df['spam']
X = df.drop(columns = ['spam'])

In [11]:
#Q1. Decision Tree Classifier Max Depth = 2 

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
clf1 = DecisionTreeClassifier(criterion = 'entropy', max_depth = 2)

In [14]:
clf1.fit(X,y)

DecisionTreeClassifier(criterion='entropy', max_depth=2)

In [15]:
round(clf1.score(X,y),3)

0.834

In [16]:
y_pred = clf1.predict(X)
from sklearn.metrics import confusion_matrix
conf1 = confusion_matrix(y,y_pred)
conf1

array([[2575,  213],
       [ 549, 1264]])

In [17]:
import numpy as np
tp1 = conf1[1,1]/sum(conf1[1,:])
fp1 = conf1 [0,1]/np.sum(conf1[0,:])
round(tp1,3), round(fp1,3)

(np.float64(0.697), np.float64(0.076))

In [18]:
#Q2. Decision Tree Classifier Max Depth =3 

In [19]:
clf2 = DecisionTreeClassifier(criterion = 'entropy', max_depth = 3)
clf2.fit(X,y)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [20]:
y_pred2 = clf2.predict(X)
conf2 = confusion_matrix(y,y_pred2)
conf2

array([[2637,  151],
       [ 560, 1253]])

In [21]:
tp2 = conf2[1,1]/sum(conf2[1,:])
fp2 = conf2[0,1]/np.sum(conf2[0,:])
round(tp2,3), round(fp2,3)

(np.float64(0.691), np.float64(0.054))

In [22]:
clf3 = DecisionTreeClassifier(criterion = 'entropy', max_depth = 4)
clf3.fit(X,y)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [23]:
#Q3. Decision Tree Classifier Max Depth = 4 

In [24]:
y_pred3 = clf3.predict(X)
conf3 = confusion_matrix(y,y_pred3)
conf3

array([[2483,  305],
       [ 213, 1600]])

In [25]:
tp3 = conf3[1,1]/sum(conf3[1,:])
fp3 = conf3[0,1]/np.sum(conf3[0,:])
round(tp3,3), round(fp3,3)

(np.float64(0.883), np.float64(0.109))

In [26]:
#Q4. Decision Tree Classifier Max Depth = 5 

In [27]:
clf4 = DecisionTreeClassifier(criterion = 'entropy', max_depth = 5)
clf4.fit(X,y)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [28]:
y_pred4 = clf4.predict(X)
conf4 = confusion_matrix(y,y_pred4)
conf4

array([[2630,  158],
       [ 289, 1524]])

In [29]:
tp4 = conf4[1,1]/sum(conf4[1,:])
fp4 = conf4[0,1]/sum(conf4[0,:])
round(tp4,3), round(fp4,3)

(np.float64(0.841), np.float64(0.057))

In [30]:
#Q5. Feature Relevance

In [31]:
imp = clf4.feature_importances_
imp

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.35897513, 0.        , 0.        , 0.00302331,
       0.0133721 , 0.        , 0.        , 0.        , 0.        ,
       0.2042085 , 0.        , 0.        , 0.        , 0.        ,
       0.00739229, 0.        , 0.        , 0.0449096 , 0.12960026,
       0.0021334 , 0.05894863, 0.00362196, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.00406665, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03431209, 0.        , 0.        , 0.11320898, 0.02222709,
       0.        ])

In [32]:
feat_list = pd.Series(imp, index= df.columns[:51])

In [33]:
ft_list = feat_list[imp>0].sort_values(ascending = False).round(3)

In [34]:
#HOMEWORK

In [35]:
# 1. Train a **logistic regression** classifier on the data of this 
# example and compare its performance to that of the classifiers presented 
# in this lecture.

In [36]:
# make a copy of current data frame to use for 
# logistic regression model.

In [37]:
data = df.copy()
data.head()

word_make  word_address  word_all  word_3d  word_our  word_over  \
0       0.00          0.64      0.64      0.0      0.32       0.00   
1       0.21          0.28      0.50      0.0      0.14       0.28   
2       0.06          0.00      0.71      0.0      1.23       0.19   
3       0.00          0.00      0.00      0.0      0.63       0.00   
4       0.00          0.00      0.00      0.0      0.63       0.00   

   word_remove  word_internet  word_order  word_mail  ...  word_original  \
0         0.00           0.00        0.00       0.00  ...           0.00   
1         0.21           0.07        0.00       0.94  ...           0.00   
2         0.19           0.12        0.64       0.25  ...           0.12   
3         0.31           0.63        0.31       0.63  ...           0.00   
4         0.31           0.63        0.31       0.63  ...           0.00   

   word_project  word_re  word_edu  word_table  word_conference  cap_ave  \
0           0.0     0.00      0.00         0.0              0.0    3.756   
1           0.0     0.00      0.00         0.0              0.0    5.114   
2           0.0     0.06      0.06         0.0              0.0    9.821   
3           0.0     0.00      0.00         0.0              0.0    3.537   
4           0.0     0.00      0.00         0.0              0.0    3.537   

   cap_long  cap_total  spam  
0        61        278     1  
1       101       1028     1  
2       485       2259     1  
3        40        191     1  
4        40        191     1  

[5 rows x 52 columns]

In [38]:
# create x and y for logistic regression model.

In [39]:
yd = data['spam']
Xd = data.drop(columns = ['spam'])

In [40]:
# Set up logistic regression model and fit it to the data.

In [41]:
from sklearn.linear_model import LogisticRegression 
Logit = LogisticRegression(max_iter = 4000)
Logit.fit(Xd,yd)

LogisticRegression(max_iter=4000)

In [42]:
#Determine the accuracy of the logistic regression model
# and compare it to the decision tree models.


In [43]:
yl_pred = Logit.predict(Xd)
conf_l = confusion_matrix(yd, yl_pred)
conf_l

array([[2638,  150],
       [ 215, 1598]])

In [44]:
acc = round((y==yl_pred).mean(),3)
print(acc)

0.921


In [71]:
tp_logit = conf_l[1,1]/sum(conf_l[1,:])
fp_logit = conf_l[0,1]/sum(conf_l[0,:])
round(tp_logit,3), round(fp_logit,3)

(np.float64(0.881), np.float64(0.054))

In [ ]:
#Accuracy of the regression model is 0.921, which is 
# high, but could be improved by tuning the model. 
# The decision tree models had accuracies of 0.918, 0.927, 
# and 0.927 for max depths of 2, 3, and 4, respectively.

In [ ]:
# 2. Change the features matrix by: (a) dropping the three `cap_` features 
# and (b) **binarizing** all the `word_` features, transforming every column
# into a dummy for the occurrence of the corresponding word, taking value 1 
# if the word occurs in the message and 0 otherwise. Based on this new 
# features matrix, train two new spam filters, one based on a logistic 
# regression model and the other one based on a decision tree model, using 
# the binarized data set. Evaluate these new filters and compare them to 
# those obtained before.

In [ ]:
#copy and check the data frame head and shape for the new assignment.

In [46]:
dhw = df.copy()
dhw.head()

word_make  word_address  word_all  word_3d  word_our  word_over  \
0       0.00          0.64      0.64      0.0      0.32       0.00   
1       0.21          0.28      0.50      0.0      0.14       0.28   
2       0.06          0.00      0.71      0.0      1.23       0.19   
3       0.00          0.00      0.00      0.0      0.63       0.00   
4       0.00          0.00      0.00      0.0      0.63       0.00   

   word_remove  word_internet  word_order  word_mail  ...  word_original  \
0         0.00           0.00        0.00       0.00  ...           0.00   
1         0.21           0.07        0.00       0.94  ...           0.00   
2         0.19           0.12        0.64       0.25  ...           0.12   
3         0.31           0.63        0.31       0.63  ...           0.00   
4         0.31           0.63        0.31       0.63  ...           0.00   

   word_project  word_re  word_edu  word_table  word_conference  cap_ave  \
0           0.0     0.00      0.00         0.0              0.0    3.756   
1           0.0     0.00      0.00         0.0              0.0    5.114   
2           0.0     0.06      0.06         0.0              0.0    9.821   
3           0.0     0.00      0.00         0.0              0.0    3.537   
4           0.0     0.00      0.00         0.0              0.0    3.537   

   cap_long  cap_total  spam  
0        61        278     1  
1       101       1028     1  
2       485       2259     1  
3        40        191     1  
4        40        191     1  

[5 rows x 52 columns]

In [47]:
dhw.shape

(4601, 52)

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 52 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   word_make        4601 non-null   float64
 1   word_address     4601 non-null   float64
 2   word_all         4601 non-null   float64
 3   word_3d          4601 non-null   float64
 4   word_our         4601 non-null   float64
 5   word_over        4601 non-null   float64
 6   word_remove      4601 non-null   float64
 7   word_internet    4601 non-null   float64
 8   word_order       4601 non-null   float64
 9   word_mail        4601 non-null   float64
 10  word_receive     4601 non-null   float64
 11  word_will        4601 non-null   float64
 12  word_people      4601 non-null   float64
 13  word_report      4601 non-null   float64
 14  word_addresses   4601 non-null   float64
 15  word_free        4601 non-null   float64
 16  word_business    4601 non-null   float64
 17  word_email       4601 non

In [ ]:
#Define the new x and y for the new models, dropping the cap_ features.

In [50]:
yhw = dhw['spam']
Xhw = dhw.drop(columns = ['spam', 'cap_ave', 'cap_long', 'cap_total'])

In [ ]:
#check which columns should be binarized.

In [52]:
Xhwkeep = Xhw.columns.str.startswith('word_')
print(Xhwkeep)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True]


In [53]:
# all columns that start with word_ should be binarized.
# Ignore Xhwkeep variable. 
# Binarize all Xhw columns. 

In [60]:
Xhw = (Xhw>0).astype(int)
Xhw.head()


word_make  word_address  word_all  word_3d  word_our  word_over  \
0          0             1         1        0         1          0   
1          1             1         1        0         1          1   
2          1             0         1        0         1          1   
3          0             0         0        0         1          0   
4          0             0         0        0         1          0   

   word_remove  word_internet  word_order  word_mail  ...  word_pm  \
0            0              0           0          0  ...        0   
1            1              1           0          1  ...        0   
2            1              1           1          1  ...        0   
3            1              1           1          1  ...        0   
4            1              1           1          1  ...        0   

   word_direct  word_cs  word_meeting  word_original  word_project  word_re  \
0            0        0             0              0             0        0   
1            0        0             0              0             0        0   
2            1        0             0              1             0        1   
3            0        0             0              0             0        0   
4            0        0             0              0             0        0   

   word_edu  word_table  word_conference  
0         0           0                0  
1         0           0                0  
2         1           0                0  
3         0           0                0  
4         0           0                0  

[5 rows x 48 columns]

In [61]:
# Set up the Decision Tree Classifier and fit it to the new data.
clhw = DecisionTreeClassifier(criterion = 'entropy', max_depth = 5)
clhw.fit(Xhw,yhw)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [62]:
round(clhw.score(Xhw,yhw),3)

0.898

In [ ]:
#Check with prediction and confusion matrix.

In [63]:
yhw_pred = clhw.predict(Xhw)
conf_hw = confusion_matrix(yhw, yhw_pred)  
conf_hw

array([[2643,  145],
       [ 325, 1488]])

In [64]:
tphw = conf_hw[1,1]/sum(conf_hw[1,:])
fphw = conf_hw[0,1]/np.sum(conf_hw[0,:])
round(tphw,3), round(fphw,3)

(np.float64(0.821), np.float64(0.052))

In [ ]:
# We see that the true positive rate of the new decision tree model is lower than 
# some of the previous models, and the false positive rate is lower. Depending on 
# the context of the problem, this may be a good tradeoff. 


In [ ]:
# Building the logistic regression model based off of the simplified features.

In [65]:
lrhw = LogisticRegression(max_iter = 4000)
lrhw.fit(Xhw,yhw)

LogisticRegression(max_iter=4000)

In [66]:
y_predlr = lrhw.predict(Xhw)
conf_lrhw = confusion_matrix(yhw, y_predlr)
conf_lrhw

array([[2654,  134],
       [ 215, 1598]])

In [ ]:
#checking the true positive and false positive rates for the logit model with the 
# binarized features.

In [69]:
tplr = conf_lrhw[1,1]/sum(conf_lrhw[1,:])
fplr = conf_lrhw[0,1]/sum(conf_lrhw[0,:])
round(tplr,3), round(fplr,3)

(np.float64(0.881), np.float64(0.048))

In [ ]:
# Using the logit model on the binarized data set, we see that the true positive 
# rate is higher than the decision tree model's true positive rate. The false 
# positive rate is lower than the decision tree model's false positive rate. 
# There is a minimal difference bewtween the logit model with and without binary
# features. Overall, considering the simplified features, the logit model performs 
# well and could be a good choice for this problem vs a decision tree model. 